name: todo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-239.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/firebase_logo.png
